#!/bin/bash
# Daily Diary Export Script
# Aggregates conversations from all AI agents into structured daily diary format

set -e

DIARIES_DIR="/root/air/qwq/6-Diaries"
QWQ_DIR="/root/air/qwq"
DATE=$(date +%Y-%m-%d)
YEAR_MONTH=$(date +%Y-%m)

# Create directory for current month
mkdir -p "$DIARIES_DIR/$YEAR_MONTH"

DIARY_FILE="$DIARIES_DIR/$YEAR_MONTH/$DATE.md"

echo "📔 Exporting Daily Diary for $DATE..."

# Initialize diary
cat > "$DIARY_FILE" << 'HEADER'
# Daily Diary

---

## 📅 Date

**DATE**

---

## 🤖 Agent Conversations

HEADER

# Replace DATE placeholder
sed -i "s/**DATE**/**$DATE**/" "$DIARY_FILE"

# Collect from qwq status (short-term memory)
if [ -f "$QWQ_DIR/0-System/status.md" ]; then
    echo "### qwq (Qwen Code) - Local" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
    echo "#### 今日快照" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
    grep -A 100 "## 今日快照" "$QWQ_DIR/0-System/status.md" | grep -B 100 "^---" | head -n -1 >> "$DIARY_FILE" 2>/dev/null || true
    echo "" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
fi

# Collect from qwq context (mid-term memory)
if [ -f "$QWQ_DIR/0-System/context.md" ]; then
    echo "#### 本周上下文" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
    grep -A 100 "## 本周快照" "$QWQ_DIR/0-System/context.md" | grep -B 100 "^---" | head -n -1 >> "$DIARY_FILE" 2>/dev/null || true
    echo "" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
fi

# Collect from mycc agent logs
MYCC_DIR="$QWQ_DIR/0-System/agents/mycc"
if [ -d "$MYCC_DIR" ]; then
    echo "### mycc (Claude Code) - Local" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
    for f in "$MYCC_DIR"/*.md; do
        if [ -f "$f" ]; then
            echo "#### $(basename "$f" .md)" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
            cat "$f" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
        fi
    done
fi

# Collect from shared-tasks completed
SHARED_COMPLETED="$QWQ_DIR/shared-tasks/completed"
if [ -d "$SHARED_COMPLETED" ] && [ "$(ls -A "$SHARED_COMPLETED" 2>/dev/null)" ]; then
    echo "### Completed Tasks (Shared)" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
    for f in "$SHARED_COMPLETED"/*.md; do
        if [ -f "$f" ]; then
            echo "#### $(basename "$f" .md)" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
            cat "$f" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
        fi
    done
fi

# Collect from tasks
TASKS_DIR="$QWQ_DIR/tasks"
if [ -d "$TASKS_DIR" ] && [ "$(ls -A "$TASKS_DIR" 2>/dev/null)" ]; then
    echo "### Active Tasks" >> "$DIARY_FILE"
    echo "" >> "$DIARY_FILE"
    for f in "$TASKS_DIR"/*.md; do
        if [ -f "$f" ]; then
            echo "#### $(basename "$f" .md)" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
            head -50 "$f" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
            echo "" >> "$DIARY_FILE"
        fi
    done
fi

# Add summary section
cat >> "$DIARY_FILE" << 'FOOTER'
---

## 📝 Summary

**Key Achievements:**
- 

**Challenges:**
- 

**Learnings:**
- 

**Next Steps:**
- 

---

## 🎯 Tomorrow's Focus

- 

---

*Generated by export-daily-diary.sh*
FOOTER

echo "✅ Diary exported to: $DIARY_FILE"
echo ""
echo "📂 Location: $DIARIES_DIR/$YEAR_MONTH/"
